# Generated by Django 3.0.5 on 2020-04-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_auto_20200414_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
