# Generated by Django 3.0.5 on 2020-04-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('progress_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.TextField()),
                ('priority', models.IntegerField()),
                ('scheduled_start', models.DateTimeField()),
                ('started_on', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('completed_on', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_manager.StatusModel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskNoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.TaskModel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDependencyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_depends_on', to='project_manager.TaskModel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_queried', to='project_manager.TaskModel')),
            ],
        ),
    ]
