# Generated by Django 3.0.5 on 2020-04-20 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasknotemodel',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='project_manager.StatusModel'),
        ),
    ]
