# Generated by Django 3.0.5 on 2020-04-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='completed_on',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='started_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
