# Generated by Django 3.0.5 on 2020-04-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager', '0002_auto_20200420_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyphraseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyphrase', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskKeyphraseLinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_manager.KeyphraseModel')),
                ('root_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_task', to='project_manager.TaskModel')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='project_manager.TaskModel')),
            ],
        ),
    ]
