# Generated by Django 3.0.5 on 2020-04-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_taskmodel_parent_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('order', models.IntegerField()),
                ('status', models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='project_manager.StatusModel')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_manager.TaskModel')),
            ],
        ),
    ]
