# Generated by Django 3.0.5 on 2020-04-21 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0006_checklistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_checklist', to='project_manager.TaskModel'),
        ),
        migrations.AlterField(
            model_name='tasknotemodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notes', to='project_manager.TaskModel'),
        ),
    ]
