# Generated by Django 3.0.5 on 2020-04-22 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_manager', '0007_auto_20200421_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='project_manager.StatusModel'),
        ),
        migrations.CreateModel(
            name='TaskPermissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perms', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='project_manager.TaskModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
