# Generated by Django 3.0.5 on 2020-04-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_auto_20200422_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project_manager.TaskModel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='priority',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='project_manager.StatusModel'),
        ),
    ]
